### PR TITLE
Map: Player list cheats

### PR DESCRIPTION
**Pull request by bigyihsuan**
Adds a collapsible cheat menu to the player list because clicking the player icon on the map is too fiddly when you're moving.

### CODE REVIEW

**Review by tom-90 — CHANGES_REQUESTED** [review]
@bigyihsuan Is there any reason this is still marked as draft? I've taken a look and tested it and it looks good. Only two points to maybe consider before I can merge this:
- In the settings, there is an option to disable cheats. It would be nice to hide the button when this is the case. You can check this setting using the `useMapSettings()` hook. In there, there is a property called `features.cheats`, which you can check before calling `actions.push` for the cheat button.
- Currently, when there are multiple players, the cheat menu willexpand or collapse for all of them at the same time when you hit the button. This is not very intuitive as the button is placed next to each player name. You could move the button to a different place and keep the functionality as is, or maybe you can change the `expand` state that you have to be an array of all of the `index` variables of the players for which the cheats should be shown.

Other than these two (small) points, it is a very nice addition.

**Comment by bigyihsuan** [comment]
> @bigyihsuan Is there any reason this is still marked as draft?

As mentioned on Discord, there was some logspam that I didn't notice until posting up the MR, so once I determine why it's happening and fix it, I'll get it and the other changes added in.

**Comment by bigyihsuan** [comment]
Just tested on a public multiplayer server, and the expander's working. Which is nice.

**Review by tom-90 — APPROVED** [review]
Looks good! I've made a small tweak in the `useState` calls in the player list file. React requires that each time the component reloads, that the same number of `useState` functions are called. Because of the loop, this would have gone wrong if a player joined or left the world while the player list was open.

I also came across a small bug while testing that made it such that the walk speed reported the incorrect value when calling `getCheats`. That was an issue in my code, and not yours. I've also fixed that.

I'll merge this and start preparing for release. Thanks for the contribution!

**Pull request merged**
